src/blog/urls.py
from django.urls import path
from blog.views import (
	create_blog_view,
	detail_blog_view,
	edit_blog_view,
    delete_post
)

app_name = 'blog'

urlpatterns = [
    path('create/', create_blog_view, name="create"),
    path('<slug>/', detail_blog_view, name="detail"),
    path('<slug>/edit/', edit_blog_view, name="edit"),
    path('<slug>/delete/',delete_post,name='delete')
 ]

src/mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from django.conf.urls.static import static
from django.conf import settings

from personal.views import (
	home_screen_view,
)

from account.views import (
    registration_view,
    logout_view,
    login_view,
    account_view,
	must_authenticate_view,
)

urlpatterns = [
    path('', home_screen_view, name="home"),
    path('account/', account_view, name="account"),
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls', 'blog')),
    path('login/', login_view, name="login"),
    path('logout/', logout_view, name="logout"),
	path('must_authenticate/', must_authenticate_view, name="must_authenticate"),
    path('register/', registration_view, name="register"),

    path('password_change/done/', auth_views.PasswordChangeDoneView.as_view(template_name='registration/password_change_done.html'), 
        name='password_change_done'),

    path('password_change/', auth_views.PasswordChangeView.as_view(template_name='registration/password_change.html'), 
        name='password_change'),

    path('pas sword_reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='registration/password_reset_done.html'),
     name='password_reset_done'),

    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('password_reset/', auth_views.PasswordResetView.as_view(), name='password_reset'),
    
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='registration/password_reset_complete.html'),
     name='password_reset_complete'),


]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/templates/snippets/base_css.html
<style type="text/css">
	body{
		background-color: #f2f2f2;
	}
</style>

src/templates/snippets/footer.html
<style type="text/css">
	.footer{
		min-height: 100px;
	}
</style>

<!-- Footer -->
<br>
<div class="d-flex flex-row align-items-center footer  bg-white border-top shadow-lg">
	<p class="m-auto">Shaxzod To'lisov Blog TZ | 2021</p>
</div>
<!-- End Footer -->


<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

src/templates/snippets/header.html
<style type="text/css">
	@media (min-width: 768px) {
	  html {
	    font-size: 16px;
	  }
	}

	.search-bar{
		max-width: 500px;
		width: 100%;
	}
	form{
		width: 100%;
	}
</style>

<!-- Header -->
<div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-white border-bottom shadow-sm">
  <h5 class="my-0 mr-md-auto font-weight-normal">
  	{% if request.user.is_authenticated %}

  		  <a class="p-2 text-dark" href="{% url 'home' %}">Xush kelibsiz, {{request.user.username}}</a>
		 
	{% endif %}
  </h5>
  <div class="search-bar mt-sm-2 mr-2">
  	<form method="get">
  		<input class="form-control" style="width: 300px;margin-left: 150px;"  type="text" name="q" id="id_q" placeholder="Qidiruv...">
  	</form>
  </div>
  <nav class="my-2 my-md-0 mr-md-3">
  	{% if request.user.is_authenticated %}
	  	<a class="p-2 text-dark" href="{% url 'blog:create' %}">Maqola yozish</a>
	    <a class="p-2 text-dark" href="{% url 'account' %}">Profile</a>
	    <a class="p-2 text-dark" href="{% url 'logout' %}">Chiqish</a>
	{% else %}
		
	    <a class="p-2 text-dark" href="{% url 'login' %}">Kirish</a>
	    <a class="btn btn-outline-primary" href="{% url 'register' %}">Register</a>
	{% endif %}	
    
  </nav>
</div>

<!-- End Header -->

<script type="text/javascript">
	document.getElementById("id_q").value = "{{query}}"
</script>